# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emotionparameters.ui',
# licensing of 'emotionparameters.ui' applies.
#
# Created: Wed Aug 28 11:41:42 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_EmotionParameters(object):
    def setupUi(self, EmotionParameters):
        EmotionParameters.setObjectName("EmotionParameters")
        EmotionParameters.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(EmotionParameters)
        self.gridLayout.setObjectName("gridLayout")
        self.okButton = QtWidgets.QPushButton(EmotionParameters)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 8, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 3)
        self.backButton = QtWidgets.QPushButton(EmotionParameters)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 5, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 3)
        self.titleLabel = QtWidgets.QLabel(EmotionParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 1, 1, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 8, 1)
        spacerItem5 = QtWidgets.QSpacerItem(688, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 5, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(EmotionParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.deleteLastButton = QtWidgets.QPushButton(self.groupBox)
        self.deleteLastButton.setObjectName("deleteLastButton")
        self.gridLayout_2.addWidget(self.deleteLastButton, 2, 9, 1, 1)
        self.questionDirectory = QtWidgets.QPushButton(self.groupBox)
        self.questionDirectory.setObjectName("questionDirectory")
        self.gridLayout_2.addWidget(self.questionDirectory, 2, 6, 1, 1)
        self.addQuestionsButton = QtWidgets.QPushButton(self.groupBox)
        self.addQuestionsButton.setObjectName("addQuestionsButton")
        self.gridLayout_2.addWidget(self.addQuestionsButton, 2, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 3, 11, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem8, 6, 1, 1, 10)
        self.videoList = QtWidgets.QTreeView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoList.sizePolicy().hasHeightForWidth())
        self.videoList.setSizePolicy(sizePolicy)
        self.videoList.setMinimumSize(QtCore.QSize(0, 200))
        self.videoList.setObjectName("videoList")
        self.gridLayout_2.addWidget(self.videoList, 3, 1, 2, 10)
        self.clearAll = QtWidgets.QPushButton(self.groupBox)
        self.clearAll.setObjectName("clearAll")
        self.gridLayout_2.addWidget(self.clearAll, 2, 10, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 3, 0, 2, 1)
        self.videosLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videosLabel.sizePolicy().hasHeightForWidth())
        self.videosLabel.setSizePolicy(sizePolicy)
        self.videosLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videosLabel.setFont(font)
        self.videosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videosLabel.setObjectName("videosLabel")
        self.gridLayout_2.addWidget(self.videosLabel, 1, 1, 1, 10)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem10, 0, 1, 1, 10)
        self.videoDirectory = QtWidgets.QPushButton(self.groupBox)
        self.videoDirectory.setObjectName("videoDirectory")
        self.gridLayout_2.addWidget(self.videoDirectory, 2, 5, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 2, 8, 1, 1)
        self.addVideoButton = QtWidgets.QPushButton(self.groupBox)
        self.addVideoButton.setObjectName("addVideoButton")
        self.gridLayout_2.addWidget(self.addVideoButton, 2, 1, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.randomizeVideosBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.randomizeVideosBox.setObjectName("randomizeVideosBox")
        self.gridLayout_4.addWidget(self.randomizeVideosBox, 2, 0, 1, 1)
        self.washoutBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.washoutBox.setObjectName("washoutBox")
        self.gridLayout_4.addWidget(self.washoutBox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_4.addWidget(self.spinBox, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 5, 1, 1, 5)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 3)

        self.retranslateUi(EmotionParameters)
        QtCore.QMetaObject.connectSlotsByName(EmotionParameters)

    def retranslateUi(self, EmotionParameters):
        EmotionParameters.setWindowTitle(QtWidgets.QApplication.translate("EmotionParameters", "EmotionTaskParameters", None, -1))
        self.okButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "OK", None, -1))
        self.backButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "Back", None, -1))
        self.titleLabel.setText(QtWidgets.QApplication.translate("EmotionParameters", "Emotion Task Parameters", None, -1))
        self.deleteLastButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "Delete Last", None, -1))
        self.questionDirectory.setText(QtWidgets.QApplication.translate("EmotionParameters", "Question Directory", None, -1))
        self.addQuestionsButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "Add Questions", None, -1))
        self.clearAll.setText(QtWidgets.QApplication.translate("EmotionParameters", "Clear All", None, -1))
        self.videosLabel.setText(QtWidgets.QApplication.translate("EmotionParameters", "Videos and Questions", None, -1))
        self.videoDirectory.setText(QtWidgets.QApplication.translate("EmotionParameters", "Video Directory", None, -1))
        self.addVideoButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "Add Video", None, -1))
        self.randomizeVideosBox.setText(QtWidgets.QApplication.translate("EmotionParameters", "Randomized Videos", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("EmotionParameters", "Task Loops", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("EmotionParameters", "Washout Time (s)", None, -1))

