# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emotionparameters.ui',
# licensing of 'emotionparameters.ui' applies.
#
# Created: Wed Jun 26 09:08:52 2019
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_EmotionParameters(object):
    def setupUi(self, EmotionParameters):
        EmotionParameters.setObjectName("EmotionParameters")
        EmotionParameters.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(EmotionParameters)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 8, 1)
        self.okButton = QtWidgets.QPushButton(EmotionParameters)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 8, 1)
        self.backButton = QtWidgets.QPushButton(EmotionParameters)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 5, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(EmotionParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.removeVideoButton = QtWidgets.QPushButton(self.groupBox)
        self.removeVideoButton.setObjectName("removeVideoButton")
        self.gridLayout_2.addWidget(self.removeVideoButton, 2, 2, 1, 1)
        self.videosLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videosLabel.setFont(font)
        self.videosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videosLabel.setObjectName("videosLabel")
        self.gridLayout_2.addWidget(self.videosLabel, 1, 1, 1, 4)
        self.InstructionsList = QtWidgets.QListView(self.groupBox)
        self.InstructionsList.setObjectName("InstructionsList")
        self.gridLayout_2.addWidget(self.InstructionsList, 3, 6, 1, 4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 2, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_4.addWidget(self.spinBox, 0, 0, 1, 1)
        self.randomizeVideosBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.randomizeVideosBox.setObjectName("randomizeVideosBox")
        self.gridLayout_4.addWidget(self.randomizeVideosBox, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 4, 6, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 9)
        self.changeInstructionsButton = QtWidgets.QPushButton(self.groupBox)
        self.changeInstructionsButton.setObjectName("changeInstructionsButton")
        self.gridLayout_2.addWidget(self.changeInstructionsButton, 2, 9, 1, 1)
        self.InstructionsLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.InstructionsLabel.setFont(font)
        self.InstructionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InstructionsLabel.setObjectName("InstructionsLabel")
        self.gridLayout_2.addWidget(self.InstructionsLabel, 1, 6, 1, 4)
        self.videoList = QtWidgets.QListView(self.groupBox)
        self.videoList.setObjectName("videoList")
        self.gridLayout_2.addWidget(self.videoList, 3, 1, 2, 4)
        self.addInstructionsButton = QtWidgets.QPushButton(self.groupBox)
        self.addInstructionsButton.setObjectName("addInstructionsButton")
        self.gridLayout_2.addWidget(self.addInstructionsButton, 2, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 10, 2, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 2, 1)
        self.changeVideoButton = QtWidgets.QPushButton(self.groupBox)
        self.changeVideoButton.setObjectName("changeVideoButton")
        self.gridLayout_2.addWidget(self.changeVideoButton, 2, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 3, 5, 2, 1)
        self.addVideoButton = QtWidgets.QPushButton(self.groupBox)
        self.addVideoButton.setObjectName("addVideoButton")
        self.gridLayout_2.addWidget(self.addVideoButton, 2, 1, 1, 1)
        self.removeInstructionsButton = QtWidgets.QPushButton(self.groupBox)
        self.removeInstructionsButton.setObjectName("removeInstructionsButton")
        self.gridLayout_2.addWidget(self.removeInstructionsButton, 2, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 8, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem9, 5, 1, 1, 9)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 3)
        self.titleLabel = QtWidgets.QLabel(EmotionParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 1, 1, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(688, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem10, 0, 1, 1, 3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem11, 7, 1, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem12, 4, 1, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem13, 2, 1, 1, 3)

        self.retranslateUi(EmotionParameters)
        QtCore.QMetaObject.connectSlotsByName(EmotionParameters)

    def retranslateUi(self, EmotionParameters):
        EmotionParameters.setWindowTitle(QtWidgets.QApplication.translate("EmotionParameters", "EmotionTaskParameters", None, -1))
        self.okButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "OK", None, -1))
        self.backButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "Back", None, -1))
        self.removeVideoButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "-", None, -1))
        self.videosLabel.setText(QtWidgets.QApplication.translate("EmotionParameters", "Videos", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("EmotionParameters", "Task Loops", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("EmotionParameters", "Control Window", None, -1))
        self.randomizeVideosBox.setText(QtWidgets.QApplication.translate("EmotionParameters", "Randomized Videos", None, -1))
        self.changeInstructionsButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "Change File", None, -1))
        self.InstructionsLabel.setText(QtWidgets.QApplication.translate("EmotionParameters", "Instructions", None, -1))
        self.addInstructionsButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "+", None, -1))
        self.changeVideoButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "Change File", None, -1))
        self.addVideoButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "+", None, -1))
        self.removeInstructionsButton.setText(QtWidgets.QApplication.translate("EmotionParameters", "-", None, -1))
        self.titleLabel.setText(QtWidgets.QApplication.translate("EmotionParameters", "Emotion Task Parameters", None, -1))

