# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emotioncontrol.ui',
# licensing of 'emotioncontrol.ui' applies.
#
# Created: Mon Sep 23 14:47:28 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_EmotionControl(object):
    def setupUi(self, EmotionControl):
        EmotionControl.setObjectName("EmotionControl")
        EmotionControl.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(EmotionControl)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(688, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 8, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 7, 1, 1, 3)
        self.titleLabel = QtWidgets.QLabel(EmotionControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 1, 1, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 8, 1)
        self.groupBox = QtWidgets.QGroupBox(EmotionControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 8, 1, 1, 4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 9, 2, 1, 2)
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.gridLayout_2.addWidget(self.startButton, 9, 1, 1, 1)
        self.videosLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videosLabel.sizePolicy().hasHeightForWidth())
        self.videosLabel.setSizePolicy(sizePolicy)
        self.videosLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videosLabel.setFont(font)
        self.videosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videosLabel.setObjectName("videosLabel")
        self.gridLayout_2.addWidget(self.videosLabel, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 5, 0, 2, 1)
        self.playingBlock = QtWidgets.QTreeView(self.groupBox)
        self.playingBlock.setMinimumSize(QtCore.QSize(0, 50))
        self.playingBlock.setMaximumSize(QtCore.QSize(16777215, 50))
        self.playingBlock.setObjectName("playingBlock")
        self.gridLayout_2.addWidget(self.playingBlock, 2, 4, 1, 1)
        self.completedBlocks = QtWidgets.QTreeView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.completedBlocks.sizePolicy().hasHeightForWidth())
        self.completedBlocks.setSizePolicy(sizePolicy)
        self.completedBlocks.setMinimumSize(QtCore.QSize(0, 200))
        self.completedBlocks.setObjectName("completedBlocks")
        self.gridLayout_2.addWidget(self.completedBlocks, 2, 1, 5, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stopButton = QtWidgets.QToolButton(self.groupBox_2)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_4.addWidget(self.stopButton, 2, 1, 1, 1)
        self.muteButton = QtWidgets.QToolButton(self.groupBox_2)
        self.muteButton.setObjectName("muteButton")
        self.gridLayout_4.addWidget(self.muteButton, 2, 3, 1, 1)
        self.playButton = QtWidgets.QToolButton(self.groupBox_2)
        self.playButton.setObjectName("playButton")
        self.gridLayout_4.addWidget(self.playButton, 2, 0, 1, 1)
        self.volumeSlider = QtWidgets.QSlider(self.groupBox_2)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.gridLayout_4.addWidget(self.volumeSlider, 2, 4, 1, 1)
        self.skipButton = QtWidgets.QToolButton(self.groupBox_2)
        self.skipButton.setObjectName("skipButton")
        self.gridLayout_4.addWidget(self.skipButton, 2, 2, 1, 1)
        self.durationLabel = QtWidgets.QLabel(self.groupBox_2)
        self.durationLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.durationLabel.setObjectName("durationLabel")
        self.gridLayout_4.addWidget(self.durationLabel, 1, 8, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 2, 8, 1, 1)
        self.fullscreenButton = QtWidgets.QPushButton(self.groupBox_2)
        self.fullscreenButton.setObjectName("fullscreenButton")
        self.gridLayout_4.addWidget(self.fullscreenButton, 2, 6, 1, 1)
        self.showButton = QtWidgets.QPushButton(self.groupBox_2)
        self.showButton.setObjectName("showButton")
        self.gridLayout_4.addWidget(self.showButton, 2, 7, 1, 1)
        self.durationSlider = QtWidgets.QSlider(self.groupBox_2)
        self.durationSlider.setMaximum(100)
        self.durationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.durationSlider.setInvertedAppearance(False)
        self.durationSlider.setInvertedControls(False)
        self.durationSlider.setObjectName("durationSlider")
        self.gridLayout_4.addWidget(self.durationSlider, 1, 0, 1, 8)
        self.gridLayout_2.addWidget(self.groupBox_2, 7, 1, 1, 4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem10, 10, 1, 1, 4)
        spacerItem11 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 5, 5, 2, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.backButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout_2.addWidget(self.backButton, 9, 4, 1, 1)
        self.quequedBlocks = QtWidgets.QTreeView(self.groupBox)
        self.quequedBlocks.setMinimumSize(QtCore.QSize(0, 150))
        self.quequedBlocks.setObjectName("quequedBlocks")
        self.gridLayout_2.addWidget(self.quequedBlocks, 4, 4, 3, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 3)

        self.retranslateUi(EmotionControl)
        QtCore.QMetaObject.connectSlotsByName(EmotionControl)

    def retranslateUi(self, EmotionControl):
        EmotionControl.setWindowTitle(QtWidgets.QApplication.translate("EmotionControl", "EmotionTaskParameters", None, -1))
        self.titleLabel.setText(QtWidgets.QApplication.translate("EmotionControl", "Emotion Task Control", None, -1))
        self.startButton.setText(QtWidgets.QApplication.translate("EmotionControl", "Start", None, -1))
        self.videosLabel.setText(QtWidgets.QApplication.translate("EmotionControl", "Quequed Blocks", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("EmotionControl", "Currently Playing", None, -1))
        self.stopButton.setText(QtWidgets.QApplication.translate("EmotionControl", "Stop", None, -1))
        self.muteButton.setText(QtWidgets.QApplication.translate("EmotionControl", "Mute", None, -1))
        self.playButton.setText(QtWidgets.QApplication.translate("EmotionControl", "Play", None, -1))
        self.skipButton.setText(QtWidgets.QApplication.translate("EmotionControl", "Skip", None, -1))
        self.durationLabel.setText(QtWidgets.QApplication.translate("EmotionControl", "00:00 / 00:00", None, -1))
        self.fullscreenButton.setText(QtWidgets.QApplication.translate("EmotionControl", "FullScreen", None, -1))
        self.showButton.setText(QtWidgets.QApplication.translate("EmotionControl", "Show", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("EmotionControl", "Completed Blocks", None, -1))
        self.backButton.setText(QtWidgets.QApplication.translate("EmotionControl", "Back", None, -1))

